services:
  open-webui:
    container_name: open-webui
    env_file:
      - .env
    ports:
      - 3032:8080
    volumes:
      - /var/opt/data/ollama/webui:/app/backend/data
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:latest
networks: {}